AppBundle\Model\Communication:
  exclusion_policy: ALL
  xml_root_name: note
  properties:
    raw:
      expose: true
      type: string
      groups: [standard, restapi]
    secret:
      expose: true
      type: string
      groups: [restapi]
    version:
      expose: true
      type: string
      until_version: 1.1
    new_version:
      expose: true
      type: string
      serialized_name: version
      since_version: 1.1
